name: smartdns-chinalist

on:
 schedule: 
   - cron: "26 20 * * 0" 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@main
    - name: CI
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        rm -f ./china.conf
        rm -f ./china.conf.gz
        wget -O ./china.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/accelerated-domains.china.conf
        wget -O ./apple.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/apple.china.conf
        wget -O ./google.conf https://raw.githubusercontent.com/felixonmars/dnsmasq-china-list/master/google.china.conf
        cat ./apple.conf >> ./china.conf 2>/dev/null
        cat ./google.conf >> ./china.conf 2>/dev/null
        rm -f ./apple.conf
        rm -f ./google.conf
        sed -i "s/^server=\/\(.*\)\/[^\/]*$/nameserver \/\1\/china/g;/^nameserver/!d" ./china.conf 2>/dev/null
        TIME=`date +%Y.%m.%d-%H:%M:%S`
        sed -i "1i#Updated at $TIME" china.conf
        gzip --best -c  china.conf >china.conf.gz
    - name: Commit files
      run: |
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "smartdns-chinalist CI." -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: 'main'
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
