name: smartdns-chinalist

on:
 schedule: 
   - cron: "26 20 * * 0" 
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@main
    - name: CI
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        rm -f ./accelerated-domains.china_no_speedtest.conf
        rm -f ./accelerated-domains.china.conf
        rm -f ./accelerated-domains.china_no_speedtest.conf.gz
        rm -f ./accelerated-domains.china.smartdns.conf.gz
        rm -f ./bogus-nxdomain.china.smartdns.conf
        git clone --depth=1 https://github.com/felixonmars/dnsmasq-china-list
        cd dnsmasq-china-list
        sed -i 's/SERVER\=114.114.114.114/SERVER\=china/g' Makefile
        sed -i 's/SMARTDNS_SPEEDTEST_MODE\=ping,tcp:80/SMARTDNS_SPEEDTEST_MODE\=none/g' Makefile
        make smartdns-domain-rules
        cat ./apple.china.domain.smartdns.conf >> ./accelerated-domains.china.domain.smartdns.conf 2>/dev/null
        cat ./google.china.domain.smartdns.conf >> ./accelerated-domains.china.domain.smartdns.conf 2>/dev/null
        rm -f ./apple.china.domain.smartdns.conf
        rm -f ./google.china.domain.smartdns.conf
        cp accelerated-domains.china.domain.smartdns.conf ../china_no_speedtest.conf
        make smartdns
        cat ./apple.china.smartdns.conf >> ./accelerated-domains.china.smartdns.conf 2>/dev/null
        cat ./google.china.smartdns.conf >> ./accelerated-domains.china.smartdns.conf 2>/dev/null
        rm -f ./apple.china.smartdns.conf
        rm -f ./google.china.smartdns.conf
        cp accelerated-domains.china.smartdns.conf ../china.conf
        cp bogus-nxdomain.china.smartdns.conf ../bogus-nxdomain.china.smartdns.conf
        cd ..
        sed -i 's/\-speed\-check\-mode none \-nameserver/\-c none \-n/g' china_no_speedtest.conf
        TIME=`date +%Y.%m.%d-%H:%M:%S`
        sed -i "1i#Updated at $TIME" china_no_speedtest.conf
        sed -i "1i#Updated at $TIME" china.conf
        sed -i "1i#Updated at $TIME" bogus-nxdomain.china.smartdns.conf
        # mv accelerated-domains.china.domain.smartdns.conf china_no_speedtest.conf
        # mv accelerated-domains.china.smartdns.conf china.conf
        gzip --best -c  china_no_speedtest.conf >china_no_speedtest.conf.gz
        gzip --best -c  china.conf >china.conf.gz
        rm -rf ./dnsmasq-china-list
    - name: Commit files
      run: |
        git add .
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "smartdns-chinalist CI." -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.PERSON_TOKEN }}
        branch: 'main'
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
